#!groovy

// Generated by IBM TransformationAdvisor
// Wed Feb 27 13:44:43 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}